#include "../Chessboard/chessboard.hpp"
#include "../Move/move.hpp"
#include "bitboard.hpp"
#include "macros.hpp"
#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <memory>